### PR TITLE
Return Increased Values.

### PR DESCRIPTION
**Pull request by egorovd**
inc and inc2 - Return Increased Values.

### CODE REVIEW

**Comment by andytill** [comment]
Thanks @egorovd!

`oneup:inc/1` and `oneup:inc2/2` were made to intentionally do as little as possible for performance reasons, I'm more worried about sending new terms across the NIF/erlang boundary than creating the long. I haven't measured the impact.

Alternatively we could have a `get_and_inc` function.

**Comment by egorovd** [comment]
Good.
Write such a function?

**Comment by andytill** [comment]
I am not planning to implement this myself.

**Comment by egorovd** [comment]
Ok.
If I write this function, will you accept the patch?

**Comment by andytill** [comment]
Yes, I'd be happy to.

**Comment by egorovd** [comment]
Done.
Check, please.

**Comment by andytill** [comment]
Looks good but the function returns the updated value.

```erlang
6> oneup:set(C,100).
3
7> oneup:get_and_inc(C).
101
```
`get_and_inc` suggests get **then** increment. I had `AtomicInteger` from the Java standard library in mind. In that, there are methods `getAndAdd` and `incrementAndGet`. Both are different ways around but both do the get in the order of the method name.

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicInteger.html#getAndAdd(int)

Could you please change the function name here to `inc_and_get`?

**Comment by egorovd** [comment]
Hello.
Forgive me for not responding for a long time.
Was busy.
Only now there is time.

Did you mean such function names?

**Comment by andytill** [comment]
Perfect thank you, and apologies for the delay!

**Pull request merged**
